---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - demo.db.com
  resources:
  - dboperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.db.com
  resources:
  - dboperators/finalizers
  verbs:
  - update
- apiGroups:
  - demo.db.com
  resources:
  - dboperators/status
  verbs:
  - get
  - patch
  - update
